---

dist: bionic

language: python
python:
  - "3.8"

before_install:
  - |
    sudo apt -y install bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev

  - |
    wget https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.deb
    sudo apt -y install ./vagrant_2.2.7_x86_64.deb
    sudo vagrant plugin install vagrant-libvirt

  - |
    sudo apt-get -y purge python3-openssl && sudo apt-get -y autoremove
    sudo apt-get update && sudo apt-get install -y ca-certificates curl gcc iproute2 python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3
    sudo pip3 install wheel
    sudo pip3 install netaddr python-vagrant yamllint testinfra flake8
    sudo pip3 install ansible ansible-lint
    sudo pip3 install -I molecule molecule-vagrant

script: travis_wait 60 sudo molecule test --scenario-name kvm
