---
- import_tasks: prelude.yml
- import_tasks: validate.yml
- name: Include install-daemon.yml
  include_tasks: install-daemon.yml
  when: libvirt_host_install_daemon | bool
- name: Include install-client.yml
  include_tasks: install-client.yml
  when:
    - not libvirt_host_install_daemon | bool
    - libvirt_host_install_client | bool
- name: Run post-install stage
  include_tasks: "{{ post_install_path }}"
  with_first_found:
    - files:
        - post-install-{{ ansible_facts.distribution }}.yml
        - post-install-{{ ansible_facts.os_family }}.yml
      skip: true
  loop_control:
    loop_var: post_install_path
- name: Include config.yml
  include_tasks: config.yml
  when: libvirt_host_install_daemon | bool
- name: Include client-config.yml
  include_tasks: client-config.yml
  when: libvirt_host_install_client | bool
- name: Include pools.yml
  include_tasks: pools.yml
  when: libvirt_host_pools is truthy
- name: Include networks.yml
  include_tasks: networks.yml
  when: libvirt_host_networks is truthy
