---

- name: Install additional packages for rbd support
  package:
    name: "{{ libvirt_host_packages_rbd_volume_pool | flatten(levels=1) }}"
    state: present
  notify: restart libvirt

- name: Create temporary file for Ceph secret
  tempfile:
    state: file
    suffix: .xml
  register: secret_tempfile

- name: Send Ceph secret
  template:
    src: ceph_secret.xml.j2
    dest: "{{ secret_tempfile.path }}"

- name: Define Ceph secret
  command: "virsh secret-define {{ secret_tempfile.path }}"

- name: Set Ceph secret value
  command: "virsh secret-set-value {{ item.name | to_uuid }} {{ item.passphrase }}"

- name: Delete temporary file
  file:
    path: "{{ secret_tempfile.path }}"
    state: absent

- name: Flush handlers
  meta: flush_handlers
