---

- name: restart libvirt
  service:
    name: libvirtd
    state: restarted
  become: True
  listen: restart libvirt

- name: Ensure libvirt storage pools are active
  virt_pool:
    name: "{{ item.name }}"
    state: active
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  with_items: "{{ libvirt_host_pools }}"
  become: True
  listen: Ensure libvirt storage pools are active

- name: Ensure libvirt networks are active
  virt_net:
    name: "{{ item.name }}"
    state: active
    uri: "{{ libvirt_host_uri | default(omit, true) }}"
  with_items: "{{ libvirt_host_networks }}"
  become: True
  listen: Ensure libvirt networks are active



