---

- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

# The socket units cannot be stopped or started if libvirt is running.
- name: stop libvirt
  ansible.builtin.service:
    name: libvirtd
    state: stopped
  become: true
  listen:
    - restart libvirt

- name: start libvirtd sockets
  ansible.builtin.service:
    name: "{{ item.service }}"
    state: "{{ item.enabled | bool | ternary('started', 'stopped') }}"
  become: true
  loop: "{{ _libvirt_socket_services }}"
  loop_control:
    label: "{{ item.service }}"
  listen:
    - restart libvirt

- name: start libvirt
  ansible.builtin.service:
    name: libvirtd
    state: started
  become: true
  listen:
    - restart libvirt

- name: reload libvirt qemu apparmor profile template
  ansible.builtin.command: apparmor_parser -r /etc/apparmor.d/libvirt/TEMPLATE.qemu
  become: true
