Vagrant.configure(2) do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.memory = "1024"
    libvirt.cpus = 1
    libvirt.driver = "kvm"
    libvirt.graphics_type = 'none'
  end
  config.ssh.insert_key = false
  config.vm.box = "centos/atomic-host"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "myvm" do |myvm|
#    myvm.vm.network :public_network,
#      :dev => "virbr0",
#      :mode => "bridge",
#      :type => "bridge"
  end
end