---
dependency:
  name: galaxy
  enabled: ${DEPENDENCY_ENABLED:-True}
  options:
    role-file: ${REQUIREMENTS_PATH:-requirements-standalone.yml}
    requirements-file: requirements-collections.yml
driver:
  name: vagrant
  provider:
    name: libvirt
platforms:
  - name: Fedora-Molecule-libvirt-host
    box: ${TESTBOX:-fedora-cloud-44-libvirt}
    box_url: ${TESTBOX_URL:-https://download.fedoraproject.org/pub/fedora/linux/releases/44/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-libvirt-44-1.7.x86_64.vagrant.libvirt.box}
    provider_options:
      driver: "kvm"
      cpus: 2
      memory: 2048
    provider_raw_config_args:
      - "storage :file, :size => '15G', :device => 'vdb'"
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${MOLECULE_PROJECT_DIRECTORY}/../community-collections:${HOME}/.ansible/collections:/usr/share/ansible/collections"
  options:
    vvv: True
  config_options:
    defaults:
      forks: 20
      remote_tmp: /tmp
    ssh_connection:
      pipelining: true
      ssh_args: -4 -o ControlMaster=auto -o ControlPersist=600s
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  options:
    v: 1
scenario:
  name: kvm
